### ISSUE TITLE
Hard coded protocol and site

### ISSUE THREAD

**Issue by paul90** [dobbs/wiki-plugin-graphviz#6]
There are a couple of places in the code that `http` is hard coded as the protocol https://github.com/dobbs/wiki-plugin-graphviz/blob/dbea92bc84bc580adefe8bc629624ab26d4405e3/client/graphviz.js#L191 https://github.com/dobbs/wiki-plugin-graphviz/blob/dbea92bc84bc580adefe8bc629624ab26d4405e3/client/graphviz.js#L195

and the site `growing.bay.wiki.org` is hard coded 
https://github.com/dobbs/wiki-plugin-graphviz/blob/dbea92bc84bc580adefe8bc629624ab26d4405e3/client/graphviz.js#L202

**Comment by WardCunningham** [comment]
I recommend this "experimental" code be removed along with the `DOT MEHAFFY` keywords that invoke it. We've now duplicated the functionality in algorithmic markup. I'll submit a pull request to remove both.

I can see value in having a number of "canned" diagrams that can be called up by name. In this case `DOT MEHAFFY` might be replaced with `DOT pattern-summary-diagram` where the slug identifies a documented about page diagram, maybe one of three or four. I think our usage of dynamic diagrams should mature before we set too many in stone by having unknown number of sites depending on them.
